"""Domain content-category lookup for the HomeSec DNS proxy.

Used to classify queried domain names into broad content categories
(adult, gambling, ads, tracking, social, gaming, streaming, news, …).
Category "malware" is assigned externally by dns_proxy.py when a domain
matches the threat-intelligence blacklist; it is not produced by this module.

The lookup is two-stage:
1. Suffix-based map (longest match wins): e.g. "www.pornhub.com" tries
   "www.pornhub.com", then "pornhub.com", then "com".
2. Keyword-pattern fallback: if no suffix matched, scan for telltale
   substrings ("analytics", "adserver", …) as a safety net for the long
   tail of tracker/ad domains that aren't explicitly listed.

Exported symbols
----------------
CATEGORY_LABELS  — dict[str, str]  human-readable label per category key
KNOWN_CATEGORIES — frozenset[str]  all known category keys
categorize_domain(domain: str) -> str
    Returns a category key string; falls back to "other".
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Category metadata
# ---------------------------------------------------------------------------

#: Human-readable labels for each category key.
CATEGORY_LABELS: dict[str, str] = {
    "malware":   "Malware",
    "adult":     "Adult",
    "gambling":  "Gambling",
    "ads":       "Ads",
    "tracking":  "Tracking",
    "social":    "Social",
    "gaming":    "Gaming",
    "streaming": "Streaming",
    "news":      "News",
    "finance":   "Finance",
    "shopping":  "Shopping",
    "travel":    "Travel",
    "cdn":       "CDN",
    "cloud":     "Cloud",
    "iot":       "IoT",
    "tech":      "Tech",
    "ai":        "AI",
    "intel":     "Threat Intel",
    "other":     "Other",
}

KNOWN_CATEGORIES: frozenset[str] = frozenset(CATEGORY_LABELS)

# ---------------------------------------------------------------------------
# Suffix → category map
# Keys are bare domain suffixes (no leading dot).  Matching is tried from
# the most-specific suffix to the least-specific (TLD).
# ---------------------------------------------------------------------------
_SUFFIX_MAP: dict[str, str] = {

    # ── Adult ────────────────────────────────────────────────────────────────
    "pornhub.com":          "adult",
    "xvideos.com":          "adult",
    "xhamster.com":         "adult",
    "xnxx.com":             "adult",
    "xnxx-cdn.com":         "adult",
    "brazzers.com":         "adult",
    "redtube.com":          "adult",
    "youporn.com":          "adult",
    "tube8.com":            "adult",
    "livejasmin.com":       "adult",
    "chaturbate.com":       "adult",
    "onlyfans.com":         "adult",
    "fapello.com":          "adult",
    "erome.com":            "adult",
    "spankbang.com":        "adult",
    "tnaflix.com":          "adult",
    "drtuber.com":          "adult",
    "porn.com":             "adult",
    "porntrex.com":         "adult",
    "hentaihaven.xxx":      "adult",
    "slutload.com":         "adult",
    "beeg.com":             "adult",
    "bang.com":             "adult",
    "reality-kings.com":    "adult",
    "bangbros.com":         "adult",
    # Adult TLDs (catch-all for any domain under these TLDs)
    "xxx":                  "adult",
    "adult":                "adult",
    "sex":                  "adult",
    "porn":                 "adult",

    # ── Gambling ─────────────────────────────────────────────────────────────
    "bet365.com":           "gambling",
    "pokerstars.com":       "gambling",
    "888casino.com":        "gambling",
    "888sport.com":         "gambling",
    "888holdings.com":      "gambling",
    "betway.com":           "gambling",
    "ladbrokes.com":        "gambling",
    "williamhill.com":      "gambling",
    "bwin.com":             "gambling",
    "unibet.com":           "gambling",
    "draftkings.com":       "gambling",
    "fanduel.com":          "gambling",
    "betonline.ag":         "gambling",
    "bovada.lv":            "gambling",
    "betfair.com":          "gambling",
    "pointsbet.com":        "gambling",
    "caesars.com":          "gambling",
    "borgataonline.com":    "gambling",
    "partycasino.com":      "gambling",
    "paddy-power.com":      "gambling",
    "betvictor.com":        "gambling",
    "coral.co.uk":          "gambling",
    "skybet.com":           "gambling",
    "mrgreen.com":          "gambling",
    "casumo.com":           "gambling",
    "leovegas.com":         "gambling",
    "pokerfull.com":        "gambling",
    "partypoker.com":       "gambling",

    # ── Ads ───────────────────────────────────────────────────────────────────
    "doubleclick.net":          "ads",
    "googlesyndication.com":    "ads",
    "googleadservices.com":     "ads",
    "adnxs.com":                "ads",
    "advertising.com":          "ads",
    "taboola.com":              "ads",
    "outbrain.com":             "ads",
    "criteo.com":               "ads",
    "criteo.net":               "ads",
    "amazon-adsystem.com":      "ads",
    "moatads.com":              "ads",
    "adroll.com":               "ads",
    "rubiconproject.com":       "ads",
    "pubmatic.com":             "ads",
    "openx.net":                "ads",
    "smaato.net":               "ads",
    "medianet.com":             "ads",
    "adcolony.com":             "ads",
    "appnexus.com":             "ads",
    "mopub.com":                "ads",
    "inmobi.com":               "ads",
    "tradedoubler.com":         "ads",
    "contextweb.com":           "ads",
    "casalemedia.com":          "ads",
    "yieldmanager.com":         "ads",
    "serving-sys.com":          "ads",
    "smartadserver.com":        "ads",
    "33across.com":             "ads",
    "bidswitch.net":            "ads",
    "adsrvr.org":               "ads",
    "lijit.com":                "ads",
    "sonobi.com":               "ads",
    "sharethrough.com":         "ads",
    "teads.tv":                 "ads",
    "ads.yahoo.com":            "ads",
    "media.net":                "ads",
    "mgid.com":                 "ads",
    "revcontent.com":           "ads",
    "triplelift.com":           "ads",
    "spotxchange.com":          "ads",
    "spotx.tv":                 "ads",
    "yieldmo.com":              "ads",
    "rhythmone.com":            "ads",
    "gumgum.com":               "ads",
    "undertone.com":            "ads",
    "indexexchange.com":        "ads",
    "adtarget.me":              "ads",
    "districtm.io":             "ads",
    "emxdgt.com":               "ads",
    "synacor.com":              "ads",
    "kontera.com":              "ads",
    "valueclick.com":           "ads",
    "zanox.com":                "ads",
    "awin.com":                 "ads",
    "impact.com":               "ads",
    "impactradius.com":         "ads",
    "shareasale.com":           "ads",
    "rakutenadvertising.com":   "ads",
    "linksynergy.com":          "ads",
    "cj.com":                   "ads",
    "a8.net":                   "ads",
    "adform.net":               "ads",
    "adform.com":               "ads",
    "bidtheatre.com":           "ads",
    "smartclip.net":            "ads",
    "yume.com":                 "ads",
    "unrulymedia.com":          "ads",
    "flashtalking.com":         "ads",
    "sizmek.com":               "ads",
    "conversantmedia.com":      "ads",
    "dotomi.com":               "ads",
    "epom.com":                 "ads",
    "zedo.com":                 "ads",
    "adtech.de":                "ads",
    "yieldlab.net":             "ads",
    "adscale.de":               "ads",
    "iponweb.net":              "ads",
    "carbonads.com":            "ads",
    "buysellads.com":           "ads",
    "trafficjunky.com":         "ads",
    "adsterra.com":             "ads",
    "propellerads.com":         "ads",
    "popads.net":               "ads",
    "popcash.net":              "ads",
    "bidvertiser.com":          "ads",
    "realmedia.com":            "ads",
    "adzerk.net":               "ads",
    "kevel.co":                 "ads",
    "thetradedesk.com":         "ads",
    "freewheel.tv":             "ads",
    "fwmrm.net":                "ads",
    "springserve.com":          "ads",
    "nativo.com":               "ads",
    "mediamath.com":            "ads",
    "iponweb.com":              "ads",
    "zeotap.com":               "ads",
    "liveramp.com":             "ads",
    "liveramp.net":             "ads",
    "acuityads.com":            "ads",
    "lkqd.net":                 "ads",
    "openx.com":                "ads",

    # ── Tracking ──────────────────────────────────────────────────────────────
    "google-analytics.com":     "tracking",
    "googletagmanager.com":     "tracking",
    "googletagservices.com":    "tracking",
    "hotjar.com":               "tracking",
    "mixpanel.com":             "tracking",
    "segment.com":              "tracking",
    "segment.io":               "tracking",
    "amplitude.com":            "tracking",
    "heap.io":                  "tracking",
    "fullstory.com":            "tracking",
    "logrocket.com":            "tracking",
    "newrelic.com":             "tracking",
    "nr-data.net":              "tracking",
    "mouseflow.com":            "tracking",
    "statcounter.com":          "tracking",
    "clicky.com":               "tracking",
    "scorecardresearch.com":    "tracking",
    "quantserve.com":           "tracking",
    "chartbeat.com":            "tracking",
    "parsely.com":              "tracking",
    "kissmetrics.com":          "tracking",
    "intercom.io":              "tracking",
    "intercom.com":             "tracking",
    "crazyegg.com":             "tracking",
    "pingdom.net":              "tracking",
    "pingdom.com":              "tracking",
    "branch.io":                "tracking",
    "appsflyer.com":            "tracking",
    "adjust.com":               "tracking",
    "kochava.com":              "tracking",
    "mparticle.com":            "tracking",
    "omtrdc.net":               "tracking",
    "demdex.net":               "tracking",
    "2o7.net":                  "tracking",
    "omniture.com":             "tracking",
    "adobedtm.com":             "tracking",
    "launchdarkly.com":         "tracking",
    "optimizely.com":           "tracking",
    "vwo.com":                  "tracking",
    "clarity.ms":               "tracking",
    "bing.com":                 "tracking",  # mostly used for analytics/ads
    "bingads.com":              "tracking",
    "bat.bing.com":             "tracking",
    "facebook.net":             "tracking",  # Facebook pixel / SDK
    "connect.facebook.net":     "tracking",
    "analytics.google.com":     "tracking",
    "piwik.pro":                "tracking",
    "matomo.cloud":             "tracking",
    "heap.com":                 "tracking",
    "sentry.io":                "tracking",
    "bugsnag.com":              "tracking",
    "rollbar.com":              "tracking",
    "datadoghq.com":            "tracking",
    "datadoghq.eu":             "tracking",
    "dynatrace.com":            "tracking",
    "elastic.co":               "tracking",
    "splunk.com":               "tracking",
    "sumologic.com":            "tracking",
    "loggly.com":               "tracking",
    "keen.io":                  "tracking",
    "clearbits.net":            "tracking",
    "Nielsen.com":              "tracking",
    "comscore.com":             "tracking",
    "nielsen.com":              "tracking",
    "addthis.com":              "tracking",
    "sharethis.com":            "tracking",
    "disqus.com":               "tracking",
    "disquscdn.com":            "tracking",
    "braze.com":                "tracking",
    "appboy.com":               "tracking",
    "onesignal.com":            "tracking",
    "push.io":                  "tracking",
    "clevertap.com":            "tracking",
    "leanplum.com":             "tracking",
    "uxcam.com":                "tracking",
    "glassbox.com":             "tracking",
    "contentsquare.com":        "tracking",
    "conviva.com":              "tracking",
    "coralogix.com":            "tracking",
    "raygun.com":               "tracking",
    "pagerduty.com":            "tracking",
    "instana.io":               "tracking",
    "instana.com":              "tracking",
    "tealiumiq.com":            "tracking",
    "tealium.com":              "tracking",
    "tealiumiq.net":            "tracking",
    "tags.tiqcdn.com":          "tracking",
    "tiqcdn.com":               "tracking",
    "qualtrics.com":            "tracking",
    "medallia.com":             "tracking",
    "surveymonkey.com":         "tracking",
    "wootric.com":              "tracking",
    "luckyorange.com":          "tracking",
    "woopra.com":               "tracking",
    "posthog.com":              "tracking",
    "plausible.io":             "tracking",
    "usefathom.com":            "tracking",
    "smartlook.com":            "tracking",
    "smartlook.cloud":          "tracking",
    "quantummetric.com":        "tracking",
    "bazaarvoice.com":          "tracking",
    "powerreviews.com":         "tracking",
    "liveperson.com":           "tracking",
    "livechatinc.com":          "tracking",
    "freshchat.com":            "tracking",
    "drift.com":                "tracking",
    "driftt.com":               "tracking",
    "appcues.com":              "tracking",
    "pendo.io":                 "tracking",
    "gainsight.com":            "tracking",
    "walkme.com":               "tracking",

    # ── Social ────────────────────────────────────────────────────────────────
    "facebook.com":             "social",
    "fbcdn.net":                "social",
    "fbsbx.com":                "social",
    "fb.com":                   "social",
    "instagram.com":            "social",
    "cdninstagram.com":         "social",
    "twitter.com":              "social",
    "t.co":                     "social",
    "twimg.com":                "social",
    "x.com":                    "social",
    "tiktok.com":               "social",
    "tiktokv.com":              "social",
    "tiktokcdn.com":            "social",
    "musically.com":            "social",
    "snapchat.com":             "social",
    "sc-cdn.net":               "social",
    "pinterest.com":            "social",
    "pinimg.com":               "social",
    "linkedin.com":             "social",
    "licdn.com":                "social",
    "reddit.com":               "social",
    "redd.it":                  "social",
    "redditmedia.com":          "social",
    "reddituploads.com":        "social",
    "tumblr.com":               "social",
    "discord.com":              "social",
    "discordapp.com":           "social",
    "discordapp.net":           "social",
    "whatsapp.com":             "social",
    "whatsapp.net":             "social",
    "telegram.org":             "social",
    "t.me":                     "social",
    "mastodon.social":          "social",
    "bsky.app":                 "social",
    "bsky.social":              "social",
    "vk.com":                   "social",
    "vk.me":                    "social",
    "ok.ru":                    "social",
    "weibo.com":                "social",
    "wechat.com":               "social",
    "wx.qq.com":                "social",
    "line.me":                  "social",
    "kakao.com":                "social",
    "viber.com":                "social",
    "signal.org":               "social",
    "guilded.gg":               "social",
    "threads.net":              "social",
    "nostr.com":                "social",
    "lemmy.world":              "social",
    "kik.com":                  "social",
    "quora.com":                "social",
    "medium.com":               "social",
    "substack.com":             "social",
    "nextdoor.com":             "social",
    "clubhouse.com":            "social",
    "mewe.com":                 "social",

    # ── Gaming ────────────────────────────────────────────────────────────────
    "steampowered.com":         "gaming",
    "steamcommunity.com":       "gaming",
    "steamstatic.com":          "gaming",
    "steamusercontent.com":     "gaming",
    "epicgames.com":            "gaming",
    "unrealengine.com":         "gaming",
    "roblox.com":               "gaming",
    "rbxcdn.com":               "gaming",
    "ea.com":                   "gaming",
    "origin.com":               "gaming",
    "battle.net":               "gaming",
    "blizzard.com":             "gaming",
    "minecraft.net":            "gaming",
    "mojang.com":               "gaming",
    "playfab.com":              "gaming",
    "xboxlive.com":             "gaming",
    "xbox.com":                 "gaming",
    "playstation.com":          "gaming",
    "psn.com":                  "gaming",
    "nintendo.com":             "gaming",
    "gog.com":                  "gaming",
    "ubisoft.com":              "gaming",
    "ubi.com":                  "gaming",
    "activision.com":           "gaming",
    "riotgames.com":            "gaming",
    "valorant.com":             "gaming",
    "leagueoflegends.com":      "gaming",
    "2k.com":                   "gaming",
    "rockstargames.com":        "gaming",
    "bethesda.net":             "gaming",
    "bethesda.com":             "gaming",
    "cdprojektred.com":         "gaming",
    "cdprojekt.com":            "gaming",
    "kongregate.com":           "gaming",
    "poki.com":                 "gaming",
    "itch.io":                  "gaming",
    "gameloft.com":             "gaming",
    "supercell.com":            "gaming",
    "twitch.tv":                "gaming",
    "jtvnw.net":                "gaming",
    "twitchsvc.net":            "gaming",
    "wargaming.net":            "gaming",
    "nexusmods.com":            "gaming",
    "curseforge.com":           "gaming",
    "overwolf.com":             "gaming",
    "ageofempires.com":         "gaming",
    "finalfantasyxiv.com":      "gaming",
    "squex.mobi":               "gaming",
    "square-enix.com":          "gaming",
    "pathofexile.com":          "gaming",
    "grindinggear.com":         "gaming",
    "humblebundle.com":         "gaming",
    "fanatical.com":            "gaming",
    "greenmanleaming.com":      "gaming",
    "indiegala.com":            "gaming",
    "gamebanana.com":           "gaming",
    "speedrun.com":             "gaming",
    "chess.com":                "gaming",
    "lichess.org":              "gaming",
    "miniclip.com":             "gaming",
    "crazygames.com":           "gaming",
    "newgrounds.com":           "gaming",
    "poki.com":                 "gaming",
    "king.com":                 "gaming",
    "supercell.net":            "gaming",
    "clashofclans.com":         "gaming",
    "nianticlabs.com":          "gaming",
    "unity3d.com":              "gaming",
    "unity.com":                "gaming",
    "beamng.com":               "gaming",
    "facepunch.com":            "gaming",
    "sega.com":                 "gaming",
    "capcom.com":               "gaming",
    "konami.com":               "gaming",
    "bandainamco.com":          "gaming",
    "wbgames.com":              "gaming",
    "arenanet.com":             "gaming",
    "guildwars2.com":           "gaming",
    "worldofwarcraft.com":      "gaming",
    "mmorpg.com":               "gaming",

    # ── Streaming ─────────────────────────────────────────────────────────────
    "netflix.com":              "streaming",
    "nflximg.net":              "streaming",
    "nflxvideo.net":            "streaming",
    "nflxext.com":              "streaming",
    "nflxso.net":               "streaming",
    "youtube.com":              "streaming",
    "youtu.be":                 "streaming",
    "googlevideo.com":          "streaming",
    "ytimg.com":                "streaming",
    "yt3.ggpht.com":            "streaming",
    "hulu.com":                 "streaming",
    "hulustream.com":           "streaming",
    "disneyplus.com":           "streaming",
    "bamgrid.com":              "streaming",
    "primevideo.com":           "streaming",
    "aiv-cdn.net":              "streaming",
    "amazonvideo.com":          "streaming",
    "spotify.com":              "streaming",
    "scdn.co":                  "streaming",
    "spotifycdn.com":           "streaming",
    "soundcloud.com":           "streaming",
    "sndcdn.com":               "streaming",
    "vimeo.com":                "streaming",
    "vimeocdn.com":             "streaming",
    "deezer.com":               "streaming",
    "tidal.com":                "streaming",
    "plex.tv":                  "streaming",
    "plexapp.com":              "streaming",
    "dailymotion.com":          "streaming",
    "crunchyroll.com":          "streaming",
    "funimation.com":           "streaming",
    "paramountplus.com":        "streaming",
    "discoveryplus.com":        "streaming",
    "hbomax.com":               "streaming",
    "max.com":                  "streaming",
    "peacocktv.com":            "streaming",
    "appletv.apple.com":        "streaming",
    "mzstatic.com":             "streaming",
    "apple-relay.com":          "streaming",
    "tv.apple.com":             "streaming",
    "music.apple.com":          "streaming",
    "podcasts.apple.com":       "streaming",
    "music.amazon.com":         "streaming",
    "tuneinyour.com":           "streaming",
    "tunein.com":               "streaming",
    "iheart.com":               "streaming",
    "iheartradio.com":          "streaming",
    "pandora.com":              "streaming",
    "pandora.net":              "streaming",
    "stitcher.com":             "streaming",
    "podbean.com":              "streaming",
    "libsyn.com":               "streaming",
    "buzzsprout.com":           "streaming",
    "anchor.fm":                "streaming",
    "mlb.com":                  "streaming",
    "nfl.com":                  "streaming",
    "nba.com":                  "streaming",
    "dazn.com":                 "streaming",
    "espn.com":                 "streaming",
    "fubo.tv":                  "streaming",
    "kodi.tv":                  "streaming",
    "pbs.org":                  "streaming",
    "curiositystream.com":      "streaming",
    "mubi.com":                 "streaming",
    "criterion.com":            "streaming",
    "shudder.com":              "streaming",
    "arrow-player.com":         "streaming",
    "britbox.com":              "streaming",
    "acorn.tv":                 "streaming",
    "iplayer.bbc.co.uk":        "streaming",
    "bbcplayer.co.uk":          "streaming",
    "itvhub.com":               "streaming",
    "channel4.com":             "streaming",
    "all4.com":                 "streaming",
    "rtve.es":                  "streaming",
    "ard.de":                   "streaming",
    "zdf.de":                   "streaming",
    "france.tv":                "streaming",
    "rai.it":                   "streaming",
    "nrk.no":                   "streaming",
    "svt.se":                   "streaming",
    "cbs.com":                  "streaming",
    "nbc.com":                  "streaming",
    "fox.com":                  "streaming",
    "abc.com":                  "streaming",
    "vudu.com":                 "streaming",
    "tubi.tv":                  "streaming",
    "plutotv.com":              "streaming",
    "crackle.com":              "streaming",
    "iqiyi.com":                "streaming",
    "youku.com":                "streaming",
    "bilibili.com":             "streaming",
    "kick.com":                 "streaming",
    "rumble.com":               "streaming",
    "audible.com":              "streaming",
    "audiblecdn.com":           "streaming",
    "amazon.com":               "shopping",   # primary use is shopping
    "amazon.co.uk":             "shopping",
    "amazon.de":                "shopping",
    "amazon.fr":                "shopping",
    "amazon.it":                "shopping",
    "amazon.es":                "shopping",
    "amazon.co.jp":             "shopping",
    "amazon.ca":                "shopping",
    "amazon.com.au":            "shopping",
    "amazon.com.br":            "shopping",
    "amazon.in":                "shopping",

    # ── News ──────────────────────────────────────────────────────────────────
    "cnn.com":                  "news",
    "bbc.com":                  "news",
    "bbc.co.uk":                "news",
    "bbci.co.uk":               "news",
    "nytimes.com":              "news",
    "theguardian.com":          "news",
    "reuters.com":              "news",
    "apnews.com":               "news",
    "washingtonpost.com":       "news",
    "foxnews.com":              "news",
    "nbcnews.com":              "news",
    "cbsnews.com":              "news",
    "bloomberg.com":            "news",
    "forbes.com":               "news",
    "techcrunch.com":           "news",
    "theverge.com":             "news",
    "arstechnica.com":          "news",
    "engadget.com":             "news",
    "wired.com":                "news",
    "gizmodo.com":              "news",
    "mashable.com":             "news",
    "zdnet.com":                "news",
    "theregister.com":          "news",
    "abcnews.go.com":           "news",
    "msn.com":                  "news",
    "usatoday.com":             "news",
    "time.com":                 "news",
    "economist.com":            "news",
    "ft.com":                   "news",
    "lemonde.fr":               "news",
    "lefigaro.fr":              "news",
    "spiegel.de":               "news",
    "faz.net":                  "news",
    "corriere.it":              "news",
    "elpais.com":               "news",
    "marca.com":                "news",
    "huffpost.com":             "news",
    "vox.com":                  "news",
    "politico.com":             "news",
    "axios.com":                "news",
    "thehill.com":              "news",
    "slate.com":                "news",
    "salon.com":                "news",
    "dailymail.co.uk":          "news",
    "thesun.co.uk":             "news",
    "mirror.co.uk":             "news",
    "independent.co.uk":        "news",
    "sky.com":                  "news",
    "itv.com":                  "news",
    "aljazeera.com":            "news",
    "dw.com":                   "news",
    "euronews.com":             "news",
    "franceinfo.fr":            "news",
    "liberation.fr":            "news",
    "20minutes.fr":             "news",
    "bild.de":                  "news",
    "welt.de":                  "news",
    "sueddeutsche.de":          "news",
    "handelsblatt.com":         "news",
    "repubblica.it":            "news",
    "elmundo.es":               "news",
    "rtve.es":                  "news",
    "publico.pt":               "news",
    "abc.net.au":               "news",
    "smh.com.au":               "news",
    "cbc.ca":                   "news",
    "globo.com":                "news",
    "folha.com.br":             "news",
    "tass.ru":                  "news",
    "rt.com":                   "news",
    "nhk.jp":                   "news",
    "yomiuri.co.jp":            "news",
    "xinhuanet.com":            "news",
    "scmp.com":                 "news",
    "haaretz.com":              "news",
    "jpost.com":                "news",
    "naver.com":                "news",
    "timesofindia.com":         "news",
    "hindustantimes.com":       "news",
    "thehindu.com":             "news",
    "ndtv.com":                 "news",
    "alarabiya.net":            "news",
    "channelnewsasia.com":      "news",
    "businessinsider.com":      "news",
    "cnbc.com":                 "news",
    "marketwatch.com":          "news",
    "wsj.com":                  "news",
    "newsweek.com":             "news",
    "vice.com":                 "news",
    "buzzfeednews.com":         "news",
    "realclearpolitics.com":    "news",

    # ── CDN / Infrastructure ─────────────────────────────────────────────────
    # Cloudflare
    "cloudflare.com":           "cdn",
    "cloudflare.net":           "cdn",
    "cf-ipfs.com":              "cdn",
    "workers.dev":              "cdn",
    "pages.dev":                "cdn",
    # AWS CloudFront
    "cloudfront.net":           "cdn",
    # Fastly
    "fastly.net":               "cdn",
    "fastlylb.net":             "cdn",
    "fastly.com":               "cdn",
    # Akamai
    "akamai.net":               "cdn",
    "akamaiedge.net":           "cdn",
    "akamaized.net":            "cdn",
    "akamaihd.net":             "cdn",
    "akamaitech.net":           "cdn",
    "edgekey.net":              "cdn",
    "edgesuite.net":            "cdn",
    "akadns.net":               "cdn",
    "akamai-staging.net":       "cdn",
    # Google CDN / static
    "gstatic.com":              "cdn",
    "googleusercontent.com":    "cdn",
    "ggpht.com":                "cdn",
    "googleapis.com":           "cdn",
    "fonts.gstatic.com":        "cdn",
    # Microsoft / Azure CDN
    "azureedge.net":            "cdn",
    "azurefd.net":              "cdn",
    "msecnd.net":               "cdn",
    "trafficmanager.net":       "cdn",
    "windows.net":              "cdn",
    # jsDelivr / npm CDN
    "jsdelivr.net":             "cdn",
    "unpkg.com":                "cdn",
    "cdnjs.cloudflare.com":     "cdn",
    "cdn.jsdelivr.net":         "cdn",
    # Bootstrap CDN
    "bootstrapcdn.com":         "cdn",
    # Amazon CloudFront / S3
    "s3.amazonaws.com":         "cdn",
    # WordPress CDN / Gravatar
    "wp.com":                   "cdn",
    "gravatar.com":             "cdn",
    "wordpress.com":            "cdn",
    # BunnyCDN
    "bunnycdn.com":             "cdn",
    "b-cdn.net":                "cdn",
    # StackPath
    "stackpathcdn.com":         "cdn",
    "hwcdn.net":                "cdn",
    # Limelight
    "limelight.com":            "cdn",
    "llnwd.net":                "cdn",
    # Verizon / EdgeCast
    "edgecastcdn.net":          "cdn",
    "edgecast.com":             "cdn",
    # Level3 / CenturyLink
    "footprint.net":            "cdn",
    "fpbns.net":                "cdn",
    # Imperva Incapsula
    "incapdns.net":             "cdn",
    # Sucuri
    "sucuri.net":               "cdn",
    # Pantheon
    "pantheon.io":              "cdn",
    # RackSpace
    "rackcdn.com":              "cdn",
    # Cloudinary
    "cloudinary.com":           "cdn",
    "res.cloudinary.com":       "cdn",
    # imgix
    "imgix.net":                "cdn",
    # jspm / skypack
    "jspm.dev":                 "cdn",
    "cdn.skypack.dev":          "cdn",
    # Vercel / Netlify edge
    "vercel-infrastructure.com": "cdn",
    "netlify.com":              "cdn",
    # Zendesk CDN
    "zdassets.com":             "cdn",
    # Shopify CDN
    "cdn.shopify.com":          "cdn",
    "shopifycdn.com":           "cdn",

    # ── Cloud / SaaS / Platform services ────────────────────────────────────
    # Google
    "google.com":               "cloud",
    "google.de":                "cloud",
    "google.fr":                "cloud",
    "google.co.uk":             "cloud",
    "google.es":                "cloud",
    "google.it":                "cloud",
    "google.ca":                "cloud",
    "google.com.au":            "cloud",
    "google.co.jp":             "cloud",
    "google.com.br":            "cloud",
    "accounts.google.com":      "cloud",
    "oauth2.googleapis.com":    "cloud",
    "mail.google.com":          "cloud",
    "drive.google.com":         "cloud",
    "docs.google.com":          "cloud",
    # Apple
    "apple.com":                "cloud",
    "icloud.com":               "cloud",
    "me.com":                   "cloud",
    "icloud-content.com":       "cloud",
    "push.apple.com":           "cloud",
    "apns.apple.com":           "cloud",
    "itunes.apple.com":         "cloud",
    "apps.apple.com":           "cloud",
    "sw-content.itunes.apple.com": "cloud",
    # Microsoft 365 / Azure
    "microsoft.com":            "cloud",
    "microsoftonline.com":      "cloud",
    "live.com":                 "cloud",
    "outlook.com":              "cloud",
    "hotmail.com":              "cloud",
    "office.com":               "cloud",
    "office365.com":            "cloud",
    "sharepoint.com":           "cloud",
    "onedrive.com":             "cloud",
    "skype.com":                "cloud",
    "teams.microsoft.com":      "cloud",
    "azure.com":                "cloud",
    "azure.net":                "cloud",
    "management.azure.com":     "cloud",
    "login.microsoftonline.com": "cloud",
    # Amazon Web Services
    "amazonaws.com":            "cloud",
    "aws.amazon.com":           "cloud",
    "awsstatic.com":            "cloud",
    # Dropbox
    "dropbox.com":              "cloud",
    "dropboxstatic.com":        "cloud",
    "dropboxusercontent.com":   "cloud",
    # Box
    "box.com":                  "cloud",
    "boxcdn.net":               "cloud",
    # Zoom
    "zoom.us":                  "cloud",
    "zoomgov.com":              "cloud",
    "zoom.com":                 "cloud",
    # Slack
    "slack.com":                "cloud",
    "slack-msgs.com":           "cloud",
    "slack-edge.com":           "cloud",
    # Notion
    "notion.so":                "cloud",
    "notion.com":               "cloud",
    # Trello / Atlassian
    "trello.com":               "cloud",
    "atlassian.com":            "cloud",
    "atlassian.net":            "cloud",
    "jira.com":                 "cloud",
    "confluence.com":           "cloud",
    # Salesforce
    "salesforce.com":           "cloud",
    "force.com":                "cloud",
    "salesforceliveagent.com":  "cloud",
    # HubSpot
    "hubspot.com":              "cloud",
    "hubapi.com":               "cloud",
    # Zendesk
    "zendesk.com":              "cloud",
    # Freshdesk
    "freshdesk.com":            "cloud",
    "freshworks.com":           "cloud",
    # ServiceNow
    "servicenow.com":           "cloud",
    # DocuSign
    "docusign.com":             "cloud",
    "docusign.net":             "cloud",
    # Twilio
    "twilio.com":               "cloud",
    "twilio.net":               "cloud",
    # SendGrid / Mailgun / Mailchimp
    "sendgrid.net":             "cloud",
    "sendgrid.com":             "cloud",
    "mailgun.com":              "cloud",
    "mailchimp.com":            "cloud",
    "mandrillapp.com":          "cloud",
    # Stripe / PayPal
    "stripe.com":               "cloud",
    "paypal.com":               "cloud",
    "paypalobjects.com":        "cloud",
    "braintreegateway.com":     "cloud",
    # Auth0 / Okta
    "auth0.com":                "cloud",
    "okta.com":                 "cloud",
    "oktacdn.com":              "cloud",
    # Firebase / Firestore
    "firebase.google.com":      "cloud",
    "firebaseapp.com":          "cloud",
    "firebaseio.com":           "cloud",
    "firebasestorage.googleapis.com": "cloud",
    # Vercel / Netlify hosting
    "vercel.app":               "cloud",
    "now.sh":                   "cloud",
    "netlify.app":              "cloud",
    # Heroku
    "heroku.com":               "cloud",
    "herokuapp.com":            "cloud",
    "herokudns.com":            "cloud",
    # DigitalOcean
    "digitalocean.com":         "cloud",
    "digitaloceanspaces.com":   "cloud",
    # Linode / Akamai Cloud
    "linode.com":               "cloud",
    # Cloudflare R2 / Pages
    "r2.dev":                   "cloud",
    # iCloud relay / Private Relay
    "mask.icloud.com":          "cloud",
    "mask-h2.icloud.com":       "cloud",


    # Email / webmail providers
    "gmail.com":                "cloud",
    "googlemail.com":           "cloud",
    "yahoo.com":                "cloud",
    "yahoo.co.jp":              "cloud",
    "ymail.com":                "cloud",
    "protonmail.com":           "cloud",
    "proton.me":                "cloud",
    "protonvpn.com":            "cloud",
    "fastmail.com":             "cloud",
    "fastmail.org":             "cloud",
    "tutanota.com":             "cloud",
    "tutanota.de":              "cloud",
    "zoho.com":                 "cloud",
    "zohocdn.com":              "cloud",
    "aol.com":                  "cloud",
    "yandex.com":               "cloud",
    "yandex.ru":                "cloud",
    "yandex.net":               "cloud",

    # ── IoT / Smart Home ─────────────────────────────────────────────────────
    # Google / Nest
    "nest.com":                 "iot",
    "nestlabs.com":             "iot",
    "home.google.com":          "iot",
    "cast.google.com":          "iot",
    # Amazon Echo / Alexa (specific subdomains — amazon.com itself → shopping)
    "amazonecho.com":           "iot",
    "device-messaging.amazon.com": "iot",
    "avs-alexa-na.amazon.com":  "iot",
    "alexa.amazon.com":         "iot",
    "api.amazonalexa.com":      "iot",
    # Ring
    "ring.com":                 "iot",
    # Philips Hue
    "meethue.com":              "iot",
    "signify.com":              "iot",
    # Sonos
    "sonos.com":                "iot",
    "sonos.net":                "iot",
    # Ecobee
    "ecobee.com":               "iot",
    # Samsung SmartThings
    "smartthings.com":          "iot",
    "samsungsmarthome.com":     "iot",
    # Tuya (large OEM behind many white-label IoT devices)
    "tuya.com":                 "iot",
    "tuyaus.com":               "iot",
    "tuyaeu.com":               "iot",
    "tuyacn.com":               "iot",
    "gw.tuyaeu.com":            "iot",
    "gw.tuyaus.com":            "iot",
    "gw.tuyacn.com":            "iot",
    "iot.tuya.com":             "iot",
    # Aqara
    "aqara.com":                "iot",
    # eWeLink / Sonoff
    "ewelink.cc":               "iot",
    "coolkit.cn":               "iot",
    # TP-Link / Kasa / Tapo
    "tplinkcloud.com":          "iot",
    "tplinknbu.com":            "iot",
    "tp-link.com":              "iot",
    # IFTTT
    "ifttt.com":                "iot",
    # Home Assistant
    "home-assistant.io":        "iot",
    "homeassistant.io":         "tech",
    "hacf.fr":                  "tech",
    "nabucasa.com":             "iot",
    # Wyze
    "wyze.com":                 "iot",
    "wyzecam.com":              "iot",
    # Arlo
    "arlo.com":                 "iot",
    "netgear.com":              "iot",
    # Shelly
    "shelly.cloud":             "iot",
    "shellycloud.com":          "iot",
    # Homey
    "homey.app":                "iot",
    "athom.com":                "iot",
    # Particle (dev boards)
    "particle.io":              "iot",
    # Lutron
    "lutron.com":               "iot",
    # Insteon
    "insteon.com":              "iot",
    # Wink
    "winkapp.com":              "iot",
    # Hubitat
    "hubitat.com":              "iot",
    # Eve / Elgato
    "evehome.com":              "iot",
    # Eufy / Anker
    "eufylife.com":             "iot",
    "anker.com":                "iot",
    # Govee
    "govee.com":                "iot",
    # Meross
    "meross.com":               "iot",
    # Roku
    "roku.com":                 "iot",
    # Chromecast (Google)
    "gvt2.com":                 "iot",
    # Apple HomeKit relay
    "homekit.apple.com":        "iot",
    # Z-Wave / Zigbee hubs
    "z-wave.me":                "iot",
    "zigbee2mqtt.io":           "iot",
    # Roomba / iRobot
    "irobot.com":               "iot",
    "irobothome.com":           "iot",
    # Xiaomi / Mi Home
    "mi.com":                   "iot",
    "xiaomi.com":               "iot",
    "miui.com":                 "iot",
    "miot.cloud":               "iot",
    # SwitchBot
    "switch-bot.com":           "iot",


    # Networking hardware (routers / APs)
    "asus.com":                 "iot",
    "asuscloud.com":            "iot",
    "dlink.com":                "iot",
    "linksys.com":              "iot",
    "belkin.com":               "iot",
    "zyxel.com":                "iot",
    "ui.com":                   "iot",   # Ubiquiti UniFi
    "ubnt.com":                 "iot",   # Ubiquiti legacy
    "gl-inet.com":              "iot",   # GL.iNet
    # IP cameras / NVRs
    "hikvision.com":            "iot",
    "dahuasecurity.com":        "iot",
    "amcrest.com":              "iot",
    "reolink.com":              "iot",
    "lorex.com":                "iot",
    "axis.com":                 "iot",
    "boschsecurity.com":        "iot",
    # Smart locks / home security
    "august.com":               "iot",
    "schlage.com":              "iot",
    "kwikset.com":              "iot",
    "simplisafe.com":           "iot",
    "vivint.com":               "iot",
    "honeywellhome.com":        "iot",
    "alarm.com":                "iot",
    # Smart speakers / AV
    "bose.com":                 "iot",
    # Samsung smart home / TVs
    "samsung.com":              "iot",
    # NAS / Network storage
    "synology.com":             "iot",
    "synology.net":             "iot",
    "myqnapcloud.com":          "iot",
    "qnap.com":                 "iot",
    "westerndigital.com":       "iot",
    "mycloud.com":              "iot",
    "seagate.com":              "iot",
    # Printers
    "hp.com":                   "iot",
    "hpconnected.com":          "iot",
    "epson.com":                "iot",
    "epsonconnect.com":         "iot",
    "canon.com":                "iot",
    "brother.com":              "iot",
    "lexmark.com":              "iot",
    "xerox.com":                "iot",
    # More home automation
    "fibaro.com":               "iot",
    "sensibo.com":              "iot",
    "ecovacs.com":              "iot",
    "roborock.com":             "iot",
    "netatmo.com":              "iot",
    "netatmo.net":              "iot",
    "withings.com":             "iot",
    "nanoleaf.me":              "iot",
    "lifx.com":                 "iot",
    "wemo.com":                 "iot",
    "tapo.com":                 "iot",
    "orvibo.com":               "iot",
    "sonoff.tech":              "iot",
    "nuki.io":                  "iot",
    "doorbird.com":             "iot",
    "bosch-smarthome.com":      "iot",
    # Fitness wearables
    "garmin.com":               "iot",
    "fitbit.com":               "iot",
    "fitbit.net":               "iot",
    "polar.com":                "iot",
    "suunto.com":               "iot",
    "peloton.com":              "iot",

    # ── Tech / Software / Dev platforms ─────────────────────────────────────
    # OS updates
    "windows.com":              "tech",
    "windowsupdate.com":        "tech",
    "update.microsoft.com":     "tech",
    "download.windowsupdate.com": "tech",
    "wns.windows.com":          "tech",
    "wdcp.microsoft.com":       "tech",
    "definitionupdates.microsoft.com": "tech",
    "dl.delivery.mp.microsoft.com": "tech",
    "swscan.apple.com":         "tech",
    "swdownload.apple.com":     "tech",
    "osxapps.itunes.apple.com": "tech",
    "xprotect.apple.com":       "tech",
    # Developer platforms
    "github.com":               "tech",
    "githubusercontent.com":    "tech",
    "githubassets.com":         "tech",
    "gitlab.com":               "tech",
    "gitlab.io":                "tech",
    "bitbucket.org":            "tech",
    "npmjs.com":                "tech",
    "registry.npmjs.org":       "tech",
    "pypi.org":                 "tech",
    "files.pythonhosted.org":   "tech",
    "packagist.org":            "tech",
    "rubygems.org":             "tech",
    "nuget.org":                "tech",
    "maven.org":                "tech",
    "mvnrepository.com":        "tech",
    "docker.io":                "tech",
    "docker.com":               "tech",
    "hub.docker.com":           "tech",
    "ghcr.io":                  "tech",
    "quay.io":                  "tech",
    # Linux distro updates
    "debian.org":               "tech",
    "ubuntu.com":               "tech",
    "canonical.com":            "tech",
    "fedoraproject.org":        "tech",
    "centos.org":               "tech",
    "archlinux.org":            "tech",
    "opensuse.org":             "tech",
    # CI / DevOps
    "circleci.com":             "tech",
    "travis-ci.com":            "tech",
    "jenkins.io":               "tech",
    "sonarqube.com":            "tech",
    "codecov.io":               "tech",
    # IDEs / Dev tools
    "jetbrains.com":            "tech",
    "visualstudio.com":         "tech",
    "vscode.dev":               "tech",
    "marketplace.visualstudio.com": "tech",
    "update.code.visualstudio.com": "tech",
    # Stack Overflow / Dev community
    "stackoverflow.com":        "tech",
    "stackexchange.com":        "tech",
    "sstatic.net":              "tech",
    "askubuntu.com":            "tech",
    # Homebrew
    "brew.sh":                  "tech",
    "formulae.brew.sh":         "tech",
    # Cloudflare 1.1.1.1 / DNS-over-HTTPS
    "cloudflare-dns.com":       "tech",
    "dns.google":               "tech",
    "doh.opendns.com":          "tech",

    # Browsers
    "mozilla.org":              "tech",
    "mozilla.net":              "tech",
    "mozilla.com":              "tech",
    "firefox.com":              "tech",
    "thunderbird.net":          "tech",
    "chromium.org":             "tech",
    "chrome.com":               "tech",
    "opera.com":                "tech",
    "brave.com":                "tech",
    "vivaldi.com":              "tech",
    "torproject.org":           "tech",
    # PKI / certificate authorities
    "letsencrypt.org":          "tech",
    "digicert.com":             "tech",
    "digicert.net":             "tech",
    "usertrust.com":            "tech",
    "comodoca.com":             "tech",
    "sectigo.com":              "tech",
    "globalsign.com":           "tech",
    "globalsign.net":           "tech",
    "pki.goog":                 "tech",
    "verisign.com":             "tech",
    "entrust.net":              "tech",
    "identrust.com":            "tech",
    "godaddy.com":              "tech",
    # NTP / time servers
    "ntp.org":                  "tech",
    "time.cloudflare.com":      "tech",
    "time.google.com":          "tech",
    "time.apple.com":           "tech",
    "time.windows.com":         "tech",
    "time.nist.gov":            "tech",
    # Antivirus / endpoint security
    "kaspersky.com":            "tech",
    "kaspersky-labs.com":       "tech",
    "mcafee.com":               "tech",
    "norton.com":               "tech",
    "nortonlifelock.com":       "tech",
    "avast.com":                "tech",
    "avg.com":                  "tech",
    "malwarebytes.com":         "tech",
    "eset.com":                 "tech",
    "bitdefender.com":          "tech",
    "sophos.com":               "tech",
    "crowdstrike.com":          "tech",
    "symantec.com":             "tech",
    # Hardware / chip vendors
    "intel.com":                "tech",
    "amd.com":                  "tech",
    "nvidia.com":               "tech",
    "qualcomm.com":             "tech",
    "arm.com":                  "tech",
    "raspberrypi.org":          "tech",
    "raspberrypi.com":          "tech",
    # VPN providers
    "nordvpn.com":              "tech",
    "expressvpn.com":           "tech",
    "mullvad.net":              "tech",
    "privateinternetaccess.com": "tech",
    "surfshark.com":            "tech",
    "ipvanish.com":             "tech",
    "tunnelbear.com":           "tech",
    "cyberghostvpn.com":        "tech",
    "windscribe.com":           "tech",
    # Package managers
    "crates.io":                "tech",
    "snapcraft.io":             "tech",
    "pkg.go.dev":               "tech",
    "sum.golang.org":           "tech",
    "proxy.golang.org":         "tech",
    "cocoapods.org":            "tech",
    # HashiCorp
    "hashicorp.com":            "tech",
    "terraform.io":             "tech",
    # Security / threat intel → own category
    "virustotal.com":           "intel",
    "shodan.io":                "intel",
    "censys.io":                "intel",
    "greynoise.io":             "intel",
    "abuseipdb.com":            "intel",
    # IP geolocation / enrichment
    "ipwho.is":                 "intel",
    "ipinfo.io":                "intel",
    "ipapi.co":                 "intel",
    "ip-api.com":               "intel",
    "maxmind.com":              "intel",
    # abuse.ch threat feeds
    "abuse.ch":                 "intel",
    "feodotracker.abuse.ch":    "intel",
    "sslbl.abuse.ch":           "intel",
    "urlhaus.abuse.ch":         "intel",
    "threatfox.abuse.ch":       "intel",
    "bazaar.abuse.ch":          "intel",
    # Other threat intel platforms
    "otx.alienvault.com":       "intel",
    "urlscan.io":               "intel",
    "phishtank.org":            "intel",
    "openphish.com":            "intel",
    "spamhaus.org":             "intel",
    "spamhaus.net":             "intel",
    "dshield.org":              "intel",
    "emerging-threats.net":     "intel",
    "rules.emergingthreats.net": "intel",
    "adguard.com":              "intel",
    "adguardteam.github.io":    "intel",
    # Search engines
    "duckduckgo.com":           "tech",
    "ddg.gg":                   "tech",
    "startpage.com":            "tech",
    "ecosia.org":               "tech",
    "baidu.com":                "tech",
    # Reference
    "wikipedia.org":            "tech",
    "wikimedia.org":            "tech",
    "archive.org":              "tech",
    "wolframalpha.com":         "tech",
    "khanacademy.org":          "tech",
    "coursera.org":             "tech",
    "udemy.com":                "tech",
    # Maps
    "here.com":                 "tech",
    "openstreetmap.org":        "tech",
    "waze.com":                 "tech",

    # ── AI / LLM services ────────────────────────────────────────────────────
    # OpenAI / ChatGPT
    "openai.com":               "ai",
    "chatgpt.com":              "ai",
    "oaiusercontent.com":       "ai",
    # GitHub Copilot
    "copilot.github.com":       "ai",
    "copilot-proxy.githubusercontent.com": "ai",
    # Google Gemini
    "gemini.google.com":        "ai",
    "aistudio.google.com":      "ai",
    "generativelanguage.googleapis.com": "ai",
    # Anthropic / Claude
    "anthropic.com":            "ai",
    "claude.ai":                "ai",
    # Mistral
    "mistral.ai":               "ai",
    # Perplexity
    "perplexity.ai":            "ai",
    # xAI / Grok
    "x.ai":                     "ai",
    "grok.com":                 "ai",
    # Cohere
    "cohere.com":               "ai",
    # Hugging Face
    "huggingface.co":           "ai",
    "hf.co":                    "ai",
    # Replicate
    "replicate.com":            "ai",
    # Stability AI
    "stability.ai":             "ai",
    # AI TLDs
    "ai":                       "ai",

    # ── Finance / Banking ────────────────────────────────────────────────────
    # US banks
    "chase.com":                "finance",
    "bankofamerica.com":        "finance",
    "wellsfargo.com":           "finance",
    "citibank.com":             "finance",
    "citi.com":                 "finance",
    "usbank.com":               "finance",
    "capitalone.com":           "finance",
    "ally.com":                 "finance",
    "discover.com":             "finance",
    "americanexpress.com":      "finance",
    "navyfederal.org":          "finance",
    "usaa.com":                 "finance",
    "truist.com":               "finance",
    # International banks
    "hsbc.com":                 "finance",
    "barclays.com":             "finance",
    "lloydsbank.com":           "finance",
    "natwest.com":              "finance",
    "santander.com":            "finance",
    "ing.com":                  "finance",
    "deutschebank.com":         "finance",
    "bnpparibas.com":           "finance",
    "societegenerale.com":      "finance",
    "intesasanpaolo.com":       "finance",
    "unicredit.com":            "finance",
    "bbva.com":                 "finance",
    "td.com":                   "finance",
    "bmo.com":                  "finance",
    "scotiabank.com":           "finance",
    "rbc.com":                  "finance",
    "nab.com.au":               "finance",
    "anz.com":                  "finance",
    "commbank.com.au":          "finance",
    "westpac.com.au":           "finance",
    # Investment / brokerage
    "fidelity.com":             "finance",
    "vanguard.com":             "finance",
    "schwab.com":               "finance",
    "tdameritrade.com":         "finance",
    "etrade.com":               "finance",
    "robinhood.com":            "finance",
    "sofi.com":                 "finance",
    "interactivebrokers.com":   "finance",
    "tradingview.com":          "finance",
    "morningstar.com":          "finance",
    "betterment.com":           "finance",
    "wealthfront.com":          "finance",
    "mint.com":                 "finance",
    "ynab.com":                 "finance",
    # Crypto
    "coinbase.com":             "finance",
    "binance.com":              "finance",
    "kraken.com":               "finance",
    "gemini.com":               "finance",
    "crypto.com":               "finance",
    "blockchain.com":           "finance",
    "etherscan.io":             "finance",
    "coindesk.com":             "finance",
    "cointelegraph.com":        "finance",
    "ledger.com":               "finance",
    "trezor.io":                "finance",
    # Fintech / payment
    "venmo.com":                "finance",
    "paypal.com":               "finance",
    "paypalobjects.com":        "finance",
    "stripe.com":               "finance",
    "square.com":               "finance",
    "squareup.com":             "finance",
    "cash.app":                 "finance",
    "cashapp.com":              "finance",
    "zelle.com":                "finance",
    "revolut.com":              "finance",
    "wise.com":                 "finance",
    "monzo.com":                "finance",
    "n26.com":                  "finance",
    "chime.com":                "finance",
    "afterpay.com":             "finance",
    "klarna.com":               "finance",
    "affirm.com":               "finance",
    # Credit bureaus
    "experian.com":             "finance",
    "equifax.com":              "finance",
    "transunion.com":           "finance",
    "creditkarma.com":          "finance",
    # Insurance
    "progressive.com":          "finance",
    "geico.com":                "finance",
    "statefarm.com":            "finance",
    "allstate.com":             "finance",
    "libertymutual.com":        "finance",
    "axa.com":                  "finance",
    "allianz.com":              "finance",
    "cigna.com":                "finance",
    "aetna.com":                "finance",
    # Finance TLDs
    "bank":                     "finance",
    "finance":                  "finance",
    "insurance":                "finance",

    # ── Shopping / E-commerce ────────────────────────────────────────────────
    "images-amazon.com":        "shopping",
    "media-amazon.com":         "shopping",
    "amazonpay.com":            "shopping",
    "ebay.com":                 "shopping",
    "ebay.co.uk":               "shopping",
    "ebay.de":                  "shopping",
    "ebaystatic.com":           "shopping",
    "ebayimg.com":              "shopping",
    "etsy.com":                 "shopping",
    "etsystatic.com":           "shopping",
    "walmart.com":              "shopping",
    "target.com":               "shopping",
    "costco.com":               "shopping",
    "homedepot.com":            "shopping",
    "lowes.com":                "shopping",
    "bestbuy.com":              "shopping",
    "newegg.com":               "shopping",
    "chewy.com":                "shopping",
    "wayfair.com":              "shopping",
    "overstock.com":            "shopping",
    "aliexpress.com":           "shopping",
    "alicdn.com":               "shopping",
    "alibaba.com":              "shopping",
    "taobao.com":               "shopping",
    "tmall.com":                "shopping",
    "jd.com":                   "shopping",
    "pinduoduo.com":            "shopping",
    "temu.com":                 "shopping",
    "shein.com":                "shopping",
    "wish.com":                 "shopping",
    "zalando.com":              "shopping",
    "zara.com":                 "shopping",
    "hm.com":                   "shopping",
    "asos.com":                 "shopping",
    "otto.de":                  "shopping",
    "fnac.com":                 "shopping",
    "tesco.com":                "shopping",
    "argos.co.uk":              "shopping",
    "shopify.com":              "shopping",
    "myshopify.com":            "shopping",
    "shopifycdn.com":           "shopping",
    "woocommerce.com":          "shopping",
    "bigcommerce.com":          "shopping",
    "squarespace.com":          "shopping",
    "wix.com":                  "shopping",
    "wixstatic.com":            "shopping",
    "instacart.com":            "shopping",
    "shop":                     "shopping",
    "store":                    "shopping",

    # ── Travel / Hospitality ─────────────────────────────────────────────────
    "booking.com":              "travel",
    "bstatic.com":              "travel",
    "expedia.com":              "travel",
    "hotels.com":               "travel",
    "trivago.com":              "travel",
    "kayak.com":                "travel",
    "priceline.com":            "travel",
    "agoda.com":                "travel",
    "skyscanner.com":           "travel",
    "skyscanner.net":           "travel",
    "kiwi.com":                 "travel",
    "momondo.com":              "travel",
    "hopper.com":               "travel",
    "airbnb.com":               "travel",
    "marriott.com":             "travel",
    "hilton.com":               "travel",
    "hyatt.com":                "travel",
    "accorhotels.com":          "travel",
    "tripadvisor.com":          "travel",
    "ta-img.com":               "travel",
    "vrbo.com":                 "travel",
    # Airlines
    "aa.com":                   "travel",
    "delta.com":                "travel",
    "united.com":               "travel",
    "southwest.com":            "travel",
    "ryanair.com":              "travel",
    "easyjet.com":              "travel",
    "wizzair.com":              "travel",
    "klm.com":                  "travel",
    "airfrance.com":            "travel",
    "lufthansa.com":            "travel",
    "britishairways.com":       "travel",
    "emirates.com":             "travel",
    "qatarairways.com":         "travel",
    "singaporeair.com":         "travel",
    "qantas.com":               "travel",
    "aircanada.com":            "travel",
    # Car rental
    "hertz.com":                "travel",
    "enterprise.com":           "travel",
    "avis.com":                 "travel",
    "europcar.com":             "travel",
    "sixt.com":                 "travel",
    # Ride sharing
    "uber.com":                 "travel",
    "lyft.com":                 "travel",
    "grab.com":                 "travel",
    "bolt.eu":                  "travel",
    # Food delivery
    "doordash.com":             "travel",
    "ubereats.com":             "travel",
    "grubhub.com":              "travel",
    "deliveroo.com":            "travel",
    "justeat.com":              "travel",
    "zomato.com":               "travel",
    "swiggy.com":               "travel",
    # Train
    "amtrak.com":               "travel",
    "eurostar.com":             "travel",
    "trainline.com":            "travel",
    "sncf.com":                 "travel",
    "bahn.de":                  "travel",
    # Travel TLDs
    "travel":                   "travel",
    "flights":                  "travel",
    "hotel":                    "travel",
}


# ---------------------------------------------------------------------------
# Keyword-pattern fallback
# Applied in order when no suffix match is found.  Only very unambiguous
# substrings are listed to keep false-positive rate near zero.
# ---------------------------------------------------------------------------
_KEYWORD_CATS: list[tuple[str, str]] = [
    # Tracking / analytics
    ("analytics",   "tracking"),
    ("telemetry",   "tracking"),
    ("tracking",    "tracking"),
    ("tracker",     "tracking"),
    ("metrics",     "tracking"),
    ("stat.",        "tracking"),
    (".stats.",     "tracking"),
    ("clicktale",   "tracking"),
    ("heatmap",     "tracking"),
    ("sessioncam",  "tracking"),
    ("beacon",      "tracking"),
    (".pixel.",     "tracking"),
    ("collect.",    "tracking"),
    ("ingest.",     "tracking"),
    # Ads
    ("adserver",    "ads"),
    ("adservice",   "ads"),
    ("adsystem",    "ads"),
    ("adtech",      "ads"),
    ("adnxs",       "ads"),
    ("adsense",     "ads"),
    ("adclick",     "ads"),
    ("doubleclick", "ads"),
    ("pagead",      "ads"),
    (".ads.",       "ads"),
    ("bidder",      "ads"),
    ("prebid",      "ads"),
    # CDN
    ("-cdn.",        "cdn"),
    (".cdn.",        "cdn"),
    ("static-cdn",  "cdn"),
    ("cdnjs",       "cdn"),
    (".static.",    "cdn"),
    (".assets.",    "cdn"),
    (".media.",     "cdn"),
    # Finance
    ("banking",     "finance"),
    (".bank.",      "finance"),
    ("payment",     "finance"),
    ("crypto",      "finance"),
    ("wallet",      "finance"),
    ("invest",      "finance"),
    ("trading",     "finance"),
    ("mortgage",    "finance"),
    # Shopping
    (".shop.",      "shopping"),
    (".store.",     "shopping"),
    ("checkout",    "shopping"),
    ("cart.",       "shopping"),
    # Travel
    ("booking",     "travel"),
    ("flights",     "travel"),
    (".hotel.",     "travel"),
    ("airline",     "travel"),
    ("reservation", "travel"),
    # Tech / network infrastructure
    ("ntp.",        "tech"),
    ("update.",     "tech"),
    ("download.",   "tech"),
    ("firmware",    "tech"),
    ("ota.",        "tech"),
]


def categorize_domain(domain: str) -> str:
    """Return the content category for *domain*.

    1. Tries suffix matches (most-specific → least-specific).
    2. Falls back to keyword patterns.
    3. Returns ``"other"`` if nothing matched.

    Examples::

        categorize_domain("www.pornhub.com")         # -> "adult"
        categorize_domain("something.xxx")           # -> "adult"
        categorize_domain("ads.doubleclick.net")     # -> "ads"
        categorize_domain("cloud.google.com")        # -> "cloud"
        categorize_domain("tuya.com")                # -> "iot"
        categorize_domain("foo.analytics.io")        # -> "tracking"  (keyword)
        categorize_domain("example.com")             # -> "other"
    """
    if not domain:
        return "other"
    parts = domain.lower().rstrip(".").split(".")
    # Stage 1: suffix map
    for i in range(len(parts)):
        candidate = ".".join(parts[i:])
        cat = _SUFFIX_MAP.get(candidate)
        if cat is not None:
            return cat
    # Stage 2: keyword patterns
    lower = domain.lower()
    for keyword, cat in _KEYWORD_CATS:
        if keyword in lower:
            return cat
    return "other"
